{
 "title": "MSK Overview",
 "description": "Prometheus monitoring for MSK cluster",
 "tags": [
  "msk",
  "kafka"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_log_Log_Value{},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Per Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages In Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",topic!=\"\", topic!~\"__amazon_msk_canary|__consumer_offsets\",instance=~\"(.*)$instance(.*)\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Sec from Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic!=\"\",topic!~\"__amazon_msk_canary|__consumer_offsets\",instance=~\"(.*)$instance(.*)\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic!=\"\",topic!~\"__amazon_msk_canary|__consumer_offsets\",instance=~\"(.*)$instance(.*)\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Per Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\",instance=~\"(.*)$instance(.*)\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under ISR Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"UnderMinIsrPartitionCount\",instance=~\"(.*)$instance(.*)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\",instance=~\"(.*)$instance(.*)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_Count{name=\"RequestsPerSec\", request=~\"Produce|FetchConsumer|FetchFollower\",instance=~\"(.*)$instance(.*)\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance,error)(rate(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\", error!=\"NONE\",instance=~\"(.*)$instance(.*)\"}[5m]))",
     "legendFormat": "{{instance}} - {{error}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Available Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/kafka/datalogs\",instance=~\"(.*)$instance(.*)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time Per Sec over the last 5 mins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, mode) (rate(node_cpu_seconds_total{instance=~\"(.*)$instance(.*)\"}[5m]))",
     "legendFormat": "{{mode}} - {{instance}}"
    }
   ]
  }
 ]
}