{
 "title": "Todos os Tópicos Kafka",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Fonte de dados", "query": "prometheus" },
   {
    "name": "topic",
    "label": "Tópico",
    "query": {
     "query": "label_values(kafka_log_Log_Value{topic!~\"__amazon_msk_canary|__consumer_offsets\"},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Métricas de Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mensagens por Segundo (Entrada)",
   "type": "timeseries",
   "description": "Mostra a taxa de mensagens recebidas por segundo em cada tópico Kafka (Métrica: MessagesInPerSec). Útil para identificar picos de produção ou problemas nos produtores.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes por Segundo (Entrada)",
   "type": "timeseries",
   "description": "Mostra a taxa de bytes recebidos por segundo em cada tópico Kafka (Métrica: BytesInPerSec). Útil para monitorar o volume de dados ingressantes.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes por Segundo (Saída)",
   "type": "timeseries",
   "description": "Mostra a taxa de bytes enviados por segundo em cada tópico Kafka (Métrica: BytesOutPerSec). Útil para monitorar o volume de dados egressantes.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Métricas de Armazenamento", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Tamanho dos Logs por Tópico",
   "type": "timeseries",
   "description": "Este gráfico exibe o tamanho total dos logs armazenados por tópico no Kafka",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_log_Log_Value{name=\"Size\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Número de Segmentos de Log",
   "type": "timeseries",
   "description": "Exibe o número de segmentos de log por partição. Um número alto pode indicar a necessidade de compactação ou limpeza (log cleanup).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_log_Log_Value{name=\"NumLogSegments\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Métricas de Replicação e ISR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Partições Under-Replicated",
   "type": "timeseries",
   "description": "Mostra partições com replicação incompleta (under-replicated). Valores acima de 0 indicam risco de perda de dados em caso de falha.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_cluster_Partition_Value{name=\"UnderReplicated\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Partições no Mínimo ISR",
   "type": "timeseries",
   "description": "Indica partições operando com o número mínimo de réplicas sincronizadas (ISR). Valores baixos podem comprometer a disponibilidade.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_cluster_Partition_Value{name=\"AtMinIsr\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Partições Under-Min ISR",
   "type": "timeseries",
   "description": "Mostra partições abaixo do número mínimo de réplicas sincronizadas (ISR). Requer atenção imediata para evitar perda de dados.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_cluster_Partition_Value{name=\"UnderMinIsr\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Métricas de Requisições e Réplicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "Requisições de Produção por Segundo",
   "type": "timeseries",
   "description": "Taxa média de requisições de produção (envio de mensagens) por tópico. Monitora a carga de trabalho dos produtores.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalProduceRequestsPerSec\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Requisições de Consumo por Segundo",
   "type": "timeseries",
   "description": "Taxa média de requisições de consumo (leitura de mensagens) por tópico. Identifica padrões de consumo anormais.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalFetchRequestsPerSec\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Métricas de Consumo (OffsetLag)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "OffsetLag - Mensagens Pendentes",
   "type": "timeseries",
   "description": "Demonstra os tópicos agrupados por consumer groups que apresentam OffsetLag, indicando atraso no processamento das mensagens.\n\nAs lacunas no gráfico são os momentos em que não existe consumidor conectado naquele consumer group",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (topic, groupId) (\n  kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\",topic=~\"$topic\"}\n)"
    }
   ]
  },
  {
   "title": "Taxa de Escrita e Réplicas Internas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Taxa de Escrita (LogEndOffset)",
   "type": "timeseries",
   "description": "Este gráfico exibe a taxa de escrita de mensagens em cada tópico do Kafka, calculada com base na variação do LogEndOffset nos últimos 5 minutos. O LogEndOffset representa o próximo offset disponível em uma partição, e sua taxa de crescimento indica a velocidade com que novos eventos estão sendo adicionados ao log.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_log_Log_Value{name=\"LogEndOffset\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag de Réplicas Internas",
   "type": "timeseries",
   "description": "Mostra o lag das réplicas internas do Kafka (ReplicaFetcherThread). É importante para monitorar a sincronização entre os brokers.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_FetcherLagMetrics_Value{name=\"ConsumerLag\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}