{
 "title": "Todos os Tópicos Kafka",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Fonte de dados", "query": "prometheus" },
   {
    "name": "topic",
    "label": "Tópico",
    "query": {
     "query": "label_values(kafka_log_Log_Value{topic!~\"__amazon_msk_canary|__consumer_offsets\"},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Métricas de Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mensagens por Segundo (Entrada)",
   "type": "timeseries",
   "description": "Mostra a taxa de mensagens recebidas por segundo em cada tópico Kafka (Métrica: MessagesInPerSec). Útil para identificar picos de produção ou problemas nos produtores.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes por Segundo (Entrada)",
   "type": "timeseries",
   "description": "Mostra a taxa de bytes recebidos por segundo em cada tópico Kafka (Métrica: BytesInPerSec). Útil para monitorar o volume de dados ingressantes.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes por Segundo (Saída)",
   "type": "timeseries",
   "description": "Mostra a taxa de bytes enviados por segundo em cada tópico Kafka (Métrica: BytesOutPerSec). Útil para monitorar o volume de dados egressantes.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Métricas de Armazenamento e Consumo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Tamanho dos Logs por Tópico",
   "type": "timeseries",
   "description": "Este gráfico exibe o tamanho total dos logs armazenados por tópico no Kafka",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_log_Log_Value{name=\"Size\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "OffsetLag - Mensagens Pendentes",
   "type": "timeseries",
   "description": "Demonstra os tópicos agrupados por consumer groups que apresentam OffsetLag, indicando atraso no processamento das mensagens.\n\nAs lacunas no gráfico são os momentos em que não existe consumidor conectado naquele consumer group",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (topic, groupId) (\n  kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\",topic=~\"$topic\"}\n)"
    }
   ]
  },
  {
   "title": "Taxa de Escrita (LogEndOffset)",
   "type": "timeseries",
   "description": "Este gráfico exibe a taxa de escrita de mensagens em cada tópico do Kafka, calculada com base na variação do LogEndOffset nos últimos 5 minutos. O LogEndOffset representa o próximo offset disponível em uma partição, e sua taxa de crescimento indica a velocidade com que novos eventos estão sendo adicionados ao log.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_log_Log_Value{name=\"LogEndOffset\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}