{
 "title": "Kubernetes SLA Dashboard",
 "tags": [
  "kubernetes",
  "sla"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Level SLA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker Nodes SLA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(kube_node_status_condition{condition=\"Ready\",status=\"true\"}[$__range:$__rate_interval]) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Service Discovery SLA",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(avg(up{job=~\"kube-dns|coredns\"})[$__range:$__rate_interval]) * 100",
     "legendFormat": "DNS Availability %"
    }
   ]
  },
  { "title": "Namespace Level SLA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "POD SLA - Availability",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(avg(kube_pod_status_ready{condition=\"true\",namespace=~\"$namespace\"}) by (namespace)[$__range:$__rate_interval]) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Ingress Level SLA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Ingress Success Rate SLA",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(sum by (exported_namespace) (rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\",status=~\"2..|3..\"}[$__rate_interval])) / sum by (exported_namespace) (rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\"}[$__rate_interval]))) * 100 > 0",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  }
 ]
}