services:
  grafana:
    build:
      context: ..
      dockerfile: .devcontainer/grafana/Dockerfile
    container_name: grafana-dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace:rw
      # Mounta os dashboards reais do seu projeto
      - ../dashboards:/var/lib/grafana/dashboards

      # Provisionamento: dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

      # Provisionamento: datasources
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin